// Maps each country route to its display metadata, hero image, flag, and the
// JSON data file (metadata + faqs) used by CountryPage.vue.
//
// Country JSON files only carry `metadata` + `faqs`; the rest of the page is
// generated by CountryPage.vue from this config + the service type.

export interface CountryFaqs {
  title: string
  subtitle: string
  items: { question: string; answer: string }[]
}

export interface CountryData {
  metadata: {
    title: string
    description: string
    keywords?: string[]
  }
  faqs: CountryFaqs
}

export type ServiceType = 'eor' | 'contractor'

export interface CountryConfig {
  /** Display name, e.g. "The Netherlands" */
  name: string
  /** EOR or Contractor management */
  type: ServiceType
  /** Hero image under /public */
  image: string
  /** Flag image under /public */
  flag: string
  /** Key into the eagerly-loaded JSON glob (filename without extension) */
  dataKey: string
}

// Eagerly import every country JSON so we can resolve by key at runtime.
const countryJson = import.meta.glob<{ default: CountryData }>(
  './*-eor.json',
  { eager: true }
)
const contractorJson = import.meta.glob<{ default: CountryData }>(
  './*-contractor.json',
  { eager: true }
)
const allJson: Record<string, { default: CountryData }> = {
  ...countryJson,
  ...contractorJson,
}

export function loadCountryData(dataKey: string): CountryData | null {
  const entry = allJson[`./${dataKey}.json`]
  return entry?.default ?? null
}

const FLAG: Record<string, string> = {
  belgium: '/countries/flag/Flag_of_Belgium.svg.png',
  china: "/countries/flag/Flag_of_the_People's_Republic_of_China.svg.webp",
  'czech-republic': '/countries/flag/Flag_of_the_Czech_Republic.svg.webp',
  france: '/countries/flag/Flag_of_France.svg.webp',
  germany: '/countries/flag/Flag_of_Germany_(3-2).svg.png',
  'hong-kong': '/countries/flag/Flag_of_Hong_Kong.svg (1).png',
  india: '/countries/flag/Flag_of_India.svg.webp',
  italy: '/countries/flag/Flag_of_Italy.svg.png',
  netherlands: '/countries/flag/Flag_of_the_Netherlands.svg.webp',
  poland: '/countries/flag/Flag_of_Poland.svg.png',
  spain: '/countries/flag/Flag_of_Spain.svg.png',
  uae: '/countries/flag/Flag_of_the_United_Arab_Emirates.svg',
  'united-kingdom': '/countries/flag/Flag-United-Kingdom.webp',
}

// EOR hero image slug differs from route slug in a few cases.
const EOR_IMG: Record<string, string> = {
  netherlands: 'eor-netherlands',
  india: 'eor-india',
  poland: 'eor-poland',
  'united-kingdom': 'eor-uk',
  germany: 'eor-germany',
  italy: 'eor-Italy',
  'czech-republic': 'eor-czech',
  france: 'eor-france',
  belgium: 'eor-belgium',
  spain: 'eor-spain',
  uae: 'eor-uae',
  'hong-kong': 'eor-hong-kong',
  china: 'eor-china',
}
const CONTRACTOR_IMG: Record<string, string> = {
  netherlands: 'contractor-netherlands',
  india: 'contractor-india',
  poland: 'contractor-poland',
  'united-kingdom': 'contractor-uk',
  germany: 'contractor-germany',
  italy: 'contractor-italy',
  'czech-republic': 'contractor-czec-republic',
  france: 'contractor-france',
  belgium: 'contractor-belgium',
  spain: 'contractor-spain',
  uae: 'contractor-uae',
}

function eorEntry(slug: string, name: string): CountryConfig {
  return {
    name,
    type: 'eor',
    image: `/countries/${EOR_IMG[slug]}.webp`,
    flag: FLAG[slug],
    dataKey: `${slug}-eor`,
  }
}
function contractorEntry(slug: string, name: string): CountryConfig {
  return {
    name,
    type: 'contractor',
    image: `/countries/${CONTRACTOR_IMG[slug]}.webp`,
    flag: FLAG[slug],
    dataKey: `${slug}-contractor`,
  }
}

// Route path → config. Keyed by the path the router uses.
export const COUNTRY_CONFIG: Record<string, CountryConfig> = {
  '/belgium': eorEntry('belgium', 'Belgium'),
  '/belgium-contractor': contractorEntry('belgium', 'Belgium'),
  '/china': eorEntry('china', 'China'),
  '/czech-republic': eorEntry('czech-republic', 'Czech Republic'),
  '/czech-republic-contractor': contractorEntry('czech-republic', 'Czech Republic'),
  '/france': eorEntry('france', 'France'),
  '/france-contractor': contractorEntry('france', 'France'),
  '/germany': eorEntry('germany', 'Germany'),
  '/germany-contractor': contractorEntry('germany', 'Germany'),
  '/hong-kong': eorEntry('hong-kong', 'Hong Kong'),
  '/india': eorEntry('india', 'India'),
  '/india-contractor': contractorEntry('india', 'India'),
  '/italy': eorEntry('italy', 'Italy'),
  '/italy-contractor': contractorEntry('italy', 'Italy'),
  '/netherlands': eorEntry('netherlands', 'The Netherlands'),
  '/netherlands-contractor': contractorEntry('netherlands', 'The Netherlands'),
  '/poland': eorEntry('poland', 'Poland'),
  '/poland-contractor': contractorEntry('poland', 'Poland'),
  '/spain': eorEntry('spain', 'Spain'),
  '/spain-contractor': contractorEntry('spain', 'Spain'),
  '/uae': eorEntry('uae', 'UAE'),
  '/uae-contractor': contractorEntry('uae', 'UAE'),
  '/united-kingdom': eorEntry('united-kingdom', 'United Kingdom'),
  '/united-kingdom-contractor': contractorEntry('united-kingdom', 'United Kingdom'),
}
